---
version: 2

updates:
  # Keep Go module dependencies up to date
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      go-dependencies:
        patterns:
          - "*"

  # Keep GitHub Actions up to date
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      github-actions:
        patterns:
          - "*"
