pkg_name=chef-load
pkg_origin=chef
pkg_version="4.0.0"
pkg_license=('UNLICENSED')
pkg_description="A tool that simulates Chef Client API load on a Chef Server and/or a Chef Automate server"
pkg_upstream_url="https://github.com/chef/chef-load"
pkg_bin_dirs=(bin)
pkg_binds_optional=(
  [automate]="port"
  [chef-server]="port"
)
pkg_scaffolding=core/scaffolding-go
scaffolding_go_base_path=github.com/chef
scaffolding_go_build_deps=(
 github.com/go-chef/chef
 github.com/naoina/toml
 github.com/satori/go.uuid
 github.com/sirupsen/logrus
)
