name: Markdown Lint

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  markdownlint:
    name: markdownlint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run markdownlint-cli2
        uses: DavidAnson/markdownlint-cli2-action@v19.1.0
        with:
          globs: "**/*.md"
