name: YAML Lint

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  yamllint:
    name: yamllint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Run yamllint
        uses: ibiqlik/action-yamllint@v3.1.1
        with:
          config_file: .yamllint.yml
          file_or_dir: .
          strict: true
